# Generated by Django 5.0.3 on 2024-03-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.IntegerField(default=1, help_text='Days in a week', verbose_name='Periodicity'),
        ),
    ]
